apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inspect-data
  namespace: inspect-ia
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 20Gi
