apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: inspect-ia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:32000/inspect-ia-frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: inspect-ia
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
